config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eWaterCycle/ewatercycle:
      branch: main
      repo: https://github.com/eWaterCycle/ewatercycle
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eWaterCycle/ewatercycle git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-amethyst-fossa.sh
        container: qc.acc_lumpy-charcoal-emu
  QC.Doc:
    repos:
      github.com/eWaterCycle/ewatercycle find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-myrtle-chin.sh
        container: qc.doc_bluesy-fuchsia-dormouse
      github.com/eWaterCycle/ewatercycle git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-viridian-argentino.sh
        container: qc.doc_hasty-myrtle-whale
      github.com/eWaterCycle/ewatercycle markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-aqua-frog.sh
        container: qc.doc_squeaky-black-robin
      github.com/eWaterCycle/ewatercycle restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-scarlet-discus.sh
        container: qc.doc_tasty-khaki-dhole
  QC.Lic:
    repos:
      github.com/eWaterCycle/ewatercycle licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-taupe-antelope.sh
        container: qc.lic_snazzy-lime-quetzal
  QC.Met:
    repos:
      github.com/eWaterCycle/ewatercycle cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-azure-tuatara.sh
        container: qc.met_lousy-tomato-quetzal
  QC.Sec:
    repos:
      github.com/eWaterCycle/ewatercycle bandit:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cerulean-gar.sh
        container: qc.sec_skimpy-cornflower-saola
  QC.Sty:
    repos:
      github.com/eWaterCycle/ewatercycle flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-ochre-hyrax.sh
        container: qc.sty_slaphappy-red-oyster
      github.com/eWaterCycle/ewatercycle jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-auburn-balinese.sh
        container: qc.sty_pokey-chestnut-coyote
  QC.Ver:
    repos:
      github.com/eWaterCycle/ewatercycle get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-brass-dachsbracke.sh
        container: qc.ver_shaggy-orchid-wolf
timeout: 5400
