config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eWaterCycle/ewatercycle:
      branch: main
      repo: https://github.com/eWaterCycle/ewatercycle
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eWaterCycle/ewatercycle git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-red-akbash.sh
        container: qc.acc_lousy-pink-harrier
  QC.Doc:
    repos:
      github.com/eWaterCycle/ewatercycle find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-salmon-panda.sh
        container: qc.doc_tacky-cornflower-iguana
      github.com/eWaterCycle/ewatercycle git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cyan-caiman.sh
        container: qc.doc_queasy-cornflower-mouse
      github.com/eWaterCycle/ewatercycle markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-cinnamon-akbash.sh
        container: qc.doc_slimy-azure-armadillo
      github.com/eWaterCycle/ewatercycle restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-myrtle-wildebeest.sh
        container: qc.doc_muggy-malachite-newfoundland
  QC.Lic:
    repos:
      github.com/eWaterCycle/ewatercycle licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-sangria-ferret.sh
        container: qc.lic_muzzy-puce-dane
  QC.Met:
    repos:
      github.com/eWaterCycle/ewatercycle cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-violet-tuatara.sh
        container: qc.met_gimpy-russet-flounder
  QC.Sec:
    repos:
      github.com/eWaterCycle/ewatercycle bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-linen-cuttlefish.sh
        container: qc.sec_skanky-lilac-guppy
  QC.Sty:
    repos:
      github.com/eWaterCycle/ewatercycle flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-gold-hippopotamus.sh
        container: qc.sty_scaly-ivory-clam
      github.com/eWaterCycle/ewatercycle jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-lilac-mongrel.sh
        container: qc.sty_surly-cobalt-gorilla
  QC.Ver:
    repos:
      github.com/eWaterCycle/ewatercycle get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-lavender-paradise.sh
        container: qc.ver_randy-pumpkin-dodo
timeout: 5400
